import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { CONFIG_PATHS, which, run, out } from '../platform.js';
import { CHAINS, PORTS, url } from '../topology.js';
import { backupOnce, restore, writeAtomic } from '../backup.js';
import { parseJsonc } from '../jsonc.js';

const dir = CONFIG_PATHS.opencodeDir;

// opencode merges config.json → opencode.json → opencode.jsonc (later wins) and
// bili's installer writes into the highest-precedence file that already exists;
// both probes accept all three names.
function configFile() {
  for (const f of ['opencode.jsonc', 'opencode.json', 'config.json']) {
    const p = path.join(dir, f);
    if (fs.existsSync(p)) return p;
  }
  return path.join(dir, 'opencode.json');
}

// headroom ships an opencode transport plugin that intercepts every outbound
// request (incl. the ChatGPT-OAuth plugin, which hardcodes chatgpt.com) and
// sends it to headroom with the original origin in x-headroom-base-url.
export function headroomTransportPlugin() {
  const tools = out('uv', ['tool', 'dir']);
  if (!tools) return null;
  const sp = path.join(tools, 'headroom-ai', 'lib');
  const py = fs.existsSync(sp) ? fs.readdirSync(sp).find((d) => d.startsWith('python')) : null;
  const candidates = [
    py && path.join(sp, py, 'site-packages', 'headroom', 'providers', 'opencode', '_dist', 'entry.opencode.js'),
    path.join(tools, 'headroom-ai', 'Lib', 'site-packages', 'headroom', 'providers', 'opencode', '_dist', 'entry.opencode.js'),
  ].filter(Boolean);
  return candidates.find((p) => fs.existsSync(p)) ?? null;
}

// A plugin entry is a package name, a path to a plugin directory, or a path to
// a .js file (V1 only). V2 also accepts { package, options } objects.
const entryRef = (p) =>
  typeof p === 'string' ? p : p && typeof p.package === 'string' ? p.package : '';

const isHeadroomPlugin = (p) => {
  const s = entryRef(p);
  if (!s) return false;
  if (/entry\.opencode\.js$/i.test(s)) return true;
  return /agent-stack-headroom/i.test(s) || (/headroom/i.test(s) && /opencode/i.test(s));
};

// V2 renamed the config key to `plugins` and only accepts directories; the V1
// line still reads `plugin`. Keep whatever shape the file already has, and ask
// opencode only when the file has neither key.
let major;
function opencodeMajor() {
  if (major === undefined) {
    const v = out('opencode', ['--version']) ?? '';
    const m = v.match(/(\d+)\s*\./);
    major = m ? Number(m[1]) : 0;
  }
  return major;
}

export function pluginKey(c) {
  if (c.plugins !== undefined) return 'plugins';
  if (c.plugin !== undefined) return 'plugin';
  return opencodeMajor() >= 2 ? 'plugins' : 'plugin';
}

// The key holds either an array of specs or an object map ({ "pkg": true }) with
// per-entry options; a projection that turns the map into an array would drop
// foreign entries, so every writer below keeps the shape it found.
export function keyEntries(raw) {
  if (Array.isArray(raw)) return raw;
  if (raw && typeof raw === 'object') return Object.keys(raw);
  return [];
}

export function pluginDirPath() {
  return path.join(dir, 'plugins', 'agent-stack-headroom');
}

// OpenCode V2 drops a configured .js file ("configured plugin path must be a
// directory") and resolves a directory through its own package.json, so we
// generate a wrapper directory instead of pointing at headroom's bundle. The
// same directory entry loads on V1, and the wrapper itself exposes both plugin
// APIs: V1 (1.18.29+) calls server(), V2 calls setup().
export function materialize(vendor) {
  const d = pluginDirPath();
  fs.mkdirSync(d, { recursive: true });
  writeAtomic(path.join(d, 'package.json'), `${JSON.stringify({
    name: 'agent-stack-headroom',
    version: '1.0.0',
    private: true,
    type: 'module',
    main: 'index.js',
  }, null, 2)}\n`);
  writeAtomic(path.join(d, 'index.js'), `// Generated by agent-stack. OpenCode loads configured plugins from a directory,
// so this wrapper carries the transport plugin that headroom ships inside its uv
// tool, and exposes it on both plugin APIs: V1 (1.18.29+) calls server(), V2
// calls setup(). 'agent-stack install' rewrites this file.
const VENDOR = ${JSON.stringify(pathToFileURL(vendor).href)};

const TOOL = 'headroom_retrieve';

// V2 declares tool inputs as JSON Schema; headroom's V1 helper builds the same
// constraint from zod (^[a-f0-9]{24}$/i). Keep the two in sync.
const TOOL_INPUT = {
  type: 'object',
  properties: {
    hash: { type: 'string', pattern: '^[a-fA-F0-9]{24}$', description: '24-character hex hash returned by headroom' },
  },
  required: ['hash'],
  additionalProperties: false,
};

let factoryPromise = null;
function headroomFactory() {
  if (!factoryPromise) {
    factoryPromise = import(VENDOR)
      .then((m) => m.default ?? m.HeadroomPlugin ?? null)
      .catch(() => null);
  }
  return factoryPromise;
}

// opencode >= 1.18.29 can load one plugin object through more than one lane (the
// V1 lane calls server(), the native lane calls setup()), so the factory - which
// installs the fetch transport - must run once per process, and the transport
// must be released once however many lanes clean up.
let hooksPromise = null;
function headroomHooks(input, options) {
  if (!hooksPromise) {
    hooksPromise = headroomFactory().then((factory) => {
      if (!factory) return null;
      try {
        return factory(input, options);
      } catch {
        return null;
      }
    });
  }
  return hooksPromise;
}

let disposed = false;
function disposeOnce(hooks) {
  if (disposed) return;
  disposed = true;
  try {
    if (typeof hooks?.dispose === 'function') hooks.dispose();
  } catch {}
}

export default {
  id: 'agent-stack-headroom',

  // V1: the factory installs the fetch transport and returns its V1 hooks.
  async server(input, options) {
    return (await headroomHooks(input, options)) ?? {};
  },

  // V2 - and the native lane of 1.18.29+: the same factory (it patches the
  // process fetch chain, which is API agnostic), then the V1 hooks are mapped
  // onto the V2 seams. On a build without those seams the transport is still
  // installed and the rest stays inert.
  async setup(ctx) {
    // headroom reads input.project?.id / input.directory, which V2 keeps under
    // ctx.location (the native lane of 1.18.x passes neither).
    const hooks = await headroomHooks(
      { directory: ctx?.location?.directory, project: ctx?.location?.project },
      ctx?.options ?? {},
    );
    if (!hooks) return () => {};

    // V1 shell.env -> ctx.shell.hook('create.before')
    const envHook = hooks['shell.env'];
    if (typeof envHook === 'function' && typeof ctx?.shell?.hook === 'function') {
      await ctx.shell.hook('create.before', (event) => {
        try {
          if (event && !event.env) event.env = {};
          envHook({}, event);
        } catch {}
      });
    }

    // V1 tool map -> ctx.tool.transform
    const tool = hooks.tool && hooks.tool[TOOL];
    if (tool && typeof ctx?.tool?.transform === 'function') {
      await ctx.tool.transform((editor) =>
        editor.add({
          name: TOOL,
          description: tool.description ?? 'Retrieve content headroom compressed out of the context',
          input: TOOL_INPUT,
          async execute(input) {
            const result = await tool.execute(input);
            return typeof result === 'string' ? { content: result } : result;
          },
        }),
      );
    }

    return () => disposeOnce(hooks);
  },
};
`);
  return d;
}

// Doctor helper: is the generated wrapper dual-API, or left over from a run
// that predates OpenCode V2 support?
export function headroomWrapperState() {
  const f = path.join(pluginDirPath(), 'index.js');
  if (!fs.existsSync(f)) return null;
  return /async setup\(/.test(fs.readFileSync(f, 'utf8')) ? 'dual' : 'v1';
}

// Older agent-stack runs wrote a bare .js path, which V2 silently drops, and
// caveman installs itself as <config>/plugins/<name>/plugin.js. A directory
// entry behaves identically as long as that folder has its own entrypoint.
export function normalizeEntry(p) {
  const s = entryRef(p);
  if (typeof p !== 'string' || !s) return p;
  const abs = path.resolve(dir, s);
  if (!/\.(m?js|cjs|ts)$/i.test(abs) || !abs.startsWith(dir + path.sep)) return p;
  const parent = path.dirname(abs);
  const hasEntry = ['package.json', 'index.js', 'index.mjs', 'index.ts'].some((n) => fs.existsSync(path.join(parent, n)));
  if (!hasEntry) return p;
  const rel = path.relative(dir, parent).split(path.sep).join('/');
  return rel.startsWith('..') ? parent : `./${rel}`;
}

export default {
  id: 'opencode',
  label: CHAINS.opencode.label,
  detect: () => Boolean(which('opencode')) || fs.existsSync(dir),

  current() {
    const f = configFile();
    if (!fs.existsSync(f)) return null;
    const c = parseJsonc(fs.readFileSync(f, 'utf8'));
    const list = [...keyEntries(c.plugins), ...keyEntries(c.plugin)];
    return list.some(isHeadroomPlugin) ? url(PORTS.headroom) : null;
  },

  apply() {
    const f = configFile();
    backupOnce(f);
    // bili runs in-process here (like dsh); its installer edits the config
    // and turns off opencode's own auto-compaction.
    const r = run('bili', ['plugin', 'install', 'opencode']);
    if (r.status !== 0) throw new Error(`bili plugin install opencode: ${r.stderr || r.stdout}`);

    const vendor = headroomTransportPlugin();
    if (!vendor) throw new Error('headroom opencode transport plugin not found (is headroom-ai installed via uv?)');
    const plugin = materialize(vendor);

    const c = fs.existsSync(f) ? parseJsonc(fs.readFileSync(f, 'utf8')) : {};
    const key = pluginKey(c);
    const raw = c[key];
    if (Array.isArray(raw)) {
      c[key] = raw.map(normalizeEntry).filter((p) => !isHeadroomPlugin(p));
      c[key].push(plugin);
    } else if (raw && typeof raw === 'object') {
      for (const k of Object.keys(raw)) if (isHeadroomPlugin(k)) delete raw[k];
      raw[plugin] = true;
    } else {
      c[key] = [plugin];
    }

    // an older agent-stack run may have left the entry in the other key
    const other = key === 'plugins' ? 'plugin' : 'plugins';
    if (Array.isArray(c[other])) {
      c[other] = c[other].filter((p) => !isHeadroomPlugin(p));
      if (!c[other].length) delete c[other];
    } else if (c[other] && typeof c[other] === 'object') {
      const map = c[other];
      for (const k of Object.keys(map)) if (isHeadroomPlugin(k)) delete map[k];
      if (!Object.keys(map).length) delete c[other];
    }

    writeAtomic(f, `${JSON.stringify(c, null, 2)}\n`);
  },

  revert() {
    run('bili', ['plugin', 'remove', 'opencode']);
    fs.rmSync(pluginDirPath(), { recursive: true, force: true });
    return restore(configFile());
  },
  ok() {
    return this.current() !== null;
  },
};
