import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { home, isWin, which, run, out } from '../platform.js';
import { CHAINS, PORTS, url } from '../topology.js';
import { backupOnce, restore, writeAtomic } from '../backup.js';
import { parseJsonc } from '../jsonc.js';

const dir = isWin && process.env.APPDATA && !fs.existsSync(path.join(home, '.config', 'opencode'))
  ? path.join(process.env.APPDATA, 'opencode')
  : path.join(home, '.config', 'opencode');

function configFile() {
  for (const f of ['opencode.jsonc', 'opencode.json']) {
    if (fs.existsSync(path.join(dir, f))) return path.join(dir, f);
  }
  return path.join(dir, 'opencode.json');
}

// headroom ships an opencode transport plugin that intercepts every outbound
// request (incl. the ChatGPT-OAuth plugin, which hardcodes chatgpt.com) and
// sends it to headroom with the original origin in x-headroom-base-url.
function headroomTransportPlugin() {
  const tools = out('uv', ['tool', 'dir']);
  if (!tools) return null;
  const sp = path.join(tools, 'headroom-ai', 'lib');
  const py = fs.existsSync(sp) ? fs.readdirSync(sp).find((d) => d.startsWith('python')) : null;
  const candidates = [
    py && path.join(sp, py, 'site-packages', 'headroom', 'providers', 'opencode', '_dist', 'entry.opencode.js'),
    path.join(tools, 'headroom-ai', 'Lib', 'site-packages', 'headroom', 'providers', 'opencode', '_dist', 'entry.opencode.js'),
  ].filter(Boolean);
  return candidates.find((p) => fs.existsSync(p)) ?? null;
}

// A plugin entry is a package name, a path to a plugin directory, or a path to
// a .js file (V1 only). V2 also accepts { package, options } objects.
const entryRef = (p) =>
  typeof p === 'string' ? p : p && typeof p.package === 'string' ? p.package : '';

const isHeadroomPlugin = (p) => {
  const s = entryRef(p);
  if (!s) return false;
  if (/entry\.opencode\.js$/i.test(s)) return true;
  return /agent-stack-headroom/i.test(s) || (/headroom/i.test(s) && /opencode/i.test(s));
};

// V2 renamed the config key to `plugins` and only accepts directories; the V1
// line still reads `plugin`. Keep whatever shape the file already has, and ask
// opencode only when the file has neither key.
let major;
function opencodeMajor() {
  if (major === undefined) {
    const v = out('opencode', ['--version']) ?? '';
    const m = v.match(/(\d+)\s*\./);
    major = m ? Number(m[1]) : 0;
  }
  return major;
}

export function pluginKey(c) {
  if (Array.isArray(c.plugins)) return 'plugins';
  if (Array.isArray(c.plugin)) return 'plugin';
  return opencodeMajor() >= 2 ? 'plugins' : 'plugin';
}

export function pluginDirPath() {
  return path.join(dir, 'plugins', 'agent-stack-headroom');
}

// OpenCode V2 drops a configured .js file ("configured plugin path must be a
// directory") and resolves a directory through its own package.json, so we
// generate a wrapper directory that re-exports headroom's bundle. The same
// directory entry loads on V1 too, which keeps both lines working.
function materialize(vendor) {
  const d = pluginDirPath();
  fs.mkdirSync(d, { recursive: true });
  writeAtomic(path.join(d, 'package.json'), `${JSON.stringify({
    name: 'agent-stack-headroom',
    version: '1.0.0',
    private: true,
    type: 'module',
    main: 'index.js',
  }, null, 2)}\n`);
  writeAtomic(path.join(d, 'index.js'),
    '// Generated by agent-stack. OpenCode loads configured plugins from a\n' +
    '// directory, so this wrapper re-exports the transport plugin that headroom\n' +
    '// ships inside its uv tool. `agent-stack install` rewrites this file.\n' +
    `export { default } from ${JSON.stringify(pathToFileURL(vendor).href)};\n`);
  return d;
}

// Older agent-stack runs wrote a bare .js path, which V2 silently drops, and
// caveman installs itself as <config>/plugins/<name>/plugin.js. A directory
// entry behaves identically as long as that folder has its own entrypoint.
export function normalizeEntry(p) {
  const s = entryRef(p);
  if (typeof p !== 'string' || !s) return p;
  const abs = path.resolve(dir, s);
  if (!/\.(m?js|cjs|ts)$/i.test(abs) || !abs.startsWith(dir + path.sep)) return p;
  const parent = path.dirname(abs);
  const hasEntry = ['package.json', 'index.js', 'index.mjs', 'index.ts'].some((n) => fs.existsSync(path.join(parent, n)));
  if (!hasEntry) return p;
  const rel = path.relative(dir, parent).split(path.sep).join('/');
  return rel.startsWith('..') ? parent : `./${rel}`;
}

export default {
  id: 'opencode',
  label: CHAINS.opencode.label,
  detect: () => Boolean(which('opencode')) || fs.existsSync(dir),

  current() {
    const f = configFile();
    if (!fs.existsSync(f)) return null;
    const c = parseJsonc(fs.readFileSync(f, 'utf8'));
    const list = [
      ...(Array.isArray(c.plugins) ? c.plugins : []),
      ...(Array.isArray(c.plugin) ? c.plugin : []),
    ];
    return list.some(isHeadroomPlugin) ? url(PORTS.headroom) : null;
  },

  apply() {
    const f = configFile();
    backupOnce(f);
    // bili runs in-process here (like dsh); its installer edits the config
    // and turns off opencode's own auto-compaction.
    const r = run('bili', ['plugin', 'install', 'opencode']);
    if (r.status !== 0) throw new Error(`bili plugin install opencode: ${r.stderr || r.stdout}`);

    const vendor = headroomTransportPlugin();
    if (!vendor) throw new Error('headroom opencode transport plugin not found (is headroom-ai installed via uv?)');
    const plugin = materialize(vendor);

    const c = fs.existsSync(f) ? parseJsonc(fs.readFileSync(f, 'utf8')) : {};
    const key = pluginKey(c);
    c[key] = (Array.isArray(c[key]) ? c[key] : []).map(normalizeEntry).filter((p) => !isHeadroomPlugin(p));
    c[key].push(plugin);

    // an older agent-stack run may have left the entry in the other key
    const other = key === 'plugins' ? 'plugin' : 'plugins';
    if (Array.isArray(c[other])) {
      c[other] = c[other].filter((p) => !isHeadroomPlugin(p));
      if (!c[other].length) delete c[other];
    }

    writeAtomic(f, `${JSON.stringify(c, null, 2)}\n`);
  },

  revert() {
    run('bili', ['plugin', 'remove', 'opencode']);
    fs.rmSync(pluginDirPath(), { recursive: true, force: true });
    return restore(configFile());
  },
  ok() {
    return this.current() !== null;
  },
};
